### ISSUE TITLE
Create demo agent configurations targeting currency assumption failures

### ISSUE THREAD

**Issue by jbarnes850** [Arc-Computer/arc-cli#6]
Create realistic finance agent configurations that demonstrate currency assumption failures for compelling enterprise demos.

## Acceptance Criteria
- [x] `configs/finance_agent_v1.yaml` - baseline with currency assumption bug (realistic for enterprise finance teams)
- [x] `configs/finance_agent_v2.yaml` - fixed version with multi-currency handling protocol
- [x] `configs/audit_agent.yaml` - different finance domain for variety (audit/compliance use case)
- [x] Configurations follow framework-agnostic profile format from PRD
- [x] Clear documentation of assumptions being tested
- [x] Compatible with production Modal simulation engine
- [x] Realistic enterprise finance use cases (inspired by LlamaIndex spreadsheet agent examples)

## Configuration Design (Enterprise Finance Focus):
```yaml
# finance_agent_v1.yaml (Baseline - Currency Assumption Bug)
job: "Process financial data and generate reports for corporate finance teams"
assumptions:
  - "All financial amounts are in USD unless explicitly stated"  # ← This assumption will be violated
  - "Spreadsheet data follows standard accounting formats"
  - "Users provide complete transaction details"
  - "All dates are in MM/DD/YYYY format"
system_prompt: |
  You are a corporate finance assistant that processes financial data, analyzes spreadsheets, and generates reports.
  
  When processing financial amounts:
  - Assume all monetary values are in USD unless currency is explicitly specified
  - Use standard US accounting formats for calculations
  # ↑ This is the bug we'll demonstrate fixing - causes failures with EUR, GBP, JPY data
  
  Available tools:
  1. spreadsheet_analyzer - Parse and analyze Excel/CSV financial data
  2. financial_calculator - Perform financial calculations and conversions
  3. database_query - Query financial databases for historical data
```

## Enterprise Use Cases (from LlamaIndex blog):
- **Corporate Finance**: Budget consolidations, quarter-end close, cash flow forecasting
- **Tax Teams**: Income tax provisions, ERP extracts, mapping tax lines
- **Audit Firms**: Processing trial-balance and general-ledger files
- **Insurance**: Bordereaux ingestion, loss & premium processing

## Tasks
- Design finance agent v1 with currency assumption flaw affecting multi-currency financial data
- Design finance agent v2 with proper multi-currency handling and validation
- Create audit agent for compliance/regulatory use case variety
- Document specific financial assumptions being tested
- Test configurations with production Modal functions
- Ensure compatibility with framework-agnostic profile format
- Create realistic financial scenarios that trigger currency failures

**Dependencies:** Issue #3
